name: 'Test artifacts'

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Exporting variables
        run: |
          content=`cat package.json`
          # the following lines are only required for multi line json
          content="${content//'%'/'%25'}"
          content="${content//$'\n'/'%0A'}"
          content="${content//$'\r'/'%0D'}"
          # end of optional handling for multi line json
          echo "::set-output name=packageJson::$content"
      - name: Importing variables
        run: |
          echo "${{fromJson(steps.set_var.outputs.packageJson)}"
          
      - name: Test creating dist files
        run: |
          dd if=/dev/zero of=test.dat  bs=1024  count=1024
          mkdir dist
          cp test.dat dist/icestudio-0.5.1w210224-linux64.AppImage
          cp test.dat dist/icestudio-0.5.1w210224-win64.exe
          cp test.dat dist/icestudio-0.5.1w210224-linux64.AppImage
          echo "*******"
          echo "${{env.version}}"
          echo "*******"
     # - name: 'Upload artifact'
     #   uses: 'actions/upload-artifact@v2'
     #   with:
     #     path: test.dat
